In [4]:
%load_ext autoreload
%autoreload 2

import requests
import pandas as pd
from gasp import weather_cpc

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import requests
from gasp.weather_cpc import parse_cpc_daily

# 1. Download a sample NOAA text file (e.g., 2011 Population Heating data)
url = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
response = requests.get(url, timeout=30)
text = response.text

# 2. Run your parser function
df = parse_cpc_daily(text)

# 3. Inspect the results
print("Success! DataFrame shape:", df.shape)
display(df.head())

Success! DataFrame shape: (0, 5)

Empty DataFrame
Columns: [date, region, measure, weighting, value]
Index: []

In [6]:
import requests
from gasp.weather_cpc import parse_cpc_daily

# 1. Download a sample NOAA text file (e.g., 2011 Population Heating data)
url = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
response = requests.get(url, timeout=30)
text = response.text

# 2. Run your parser function
df = parse_cpc_daily(text)

# 3. Inspect the results
print("Success! DataFrame shape:", df.shape)
display(df.head())

Success! DataFrame shape: (0, 5)

Empty DataFrame
Columns: [date, region, measure, weighting, value]
Index: []

In [7]:
import requests
import io
import pandas as pd

# 1. Download the file text
url = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
text = requests.get(url, timeout=30).text
lines = text.strip().splitlines()

# 2. Find where the header/date row is
header_end_idx = 0
for idx, line in enumerate(lines):
    if line.lstrip().startswith(("YYYYMMDD", "Date")):
        header_end_idx = idx
        print(f"Found header at index: {idx}")
        print(f"Header line: {line}")
        break

# 3. Test reading the table text into pandas
data_text = "\n".join(lines[header_end_idx:])
df_test = pd.read_csv(io.StringIO(data_text), sep=r"\s+")

print("\nDataFrame shape:", df_test.shape)
display(df_test.head())

DataFrame shape: (13, 5)

,Product:,Daily,Heating,Degree,Days
0,Regions:,Regions::CensusDivisions,NaN,NaN,NaN
1,Weights:,Population,NaN,NaN,NaN
2,Region|20110101|20110102|20110103|20110104|201...,NaN,NaN,NaN,NaN
3,1|24|23|34|38|38|42|42|39|37|39|43|40|40|48|49...,NaN,NaN,NaN,NaN
4,2|25|25|36|35|37|42|40|44|41|41|43|42|42|46|44...,NaN,NaN,NaN,NaN

In [8]:
import requests
import io
import pandas as pd

# 1. Download the file text
url = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
text = requests.get(url, timeout=30).text
lines = text.strip().splitlines()

# 2. Find where the header/date row is
header_end_idx = 0
for idx, line in enumerate(lines):
    if line.lstrip().startswith(("YYYYMMDD", "Date")):
        header_end_idx = idx
        print(f"Found header at index: {idx}")
        print(f"Header line: {line}")
        break

# 3. Test reading the table text into pandas
data_text = "\n".join(lines[header_end_idx:])
df_test = pd.read_csv(io.StringIO(data_text), sep=r"\s+")

print("\nDataFrame shape:", df_test.shape)
display(df_test.head())

DataFrame shape: (13, 5)

,Product:,Daily,Heating,Degree,Days
0,Regions:,Regions::CensusDivisions,NaN,NaN,NaN
1,Weights:,Population,NaN,NaN,NaN
2,Region|20110101|20110102|20110103|20110104|201...,NaN,NaN,NaN,NaN
3,1|24|23|34|38|38|42|42|39|37|39|43|40|40|48|49...,NaN,NaN,NaN,NaN
4,2|25|25|36|35|37|42|40|44|41|41|43|42|42|46|44...,NaN,NaN,NaN,NaN

In [9]:
import importlib
import gasp.weather_cpc
importlib.reload(gasp.weather_cpc)
from gasp.weather_cpc import parse_cpc_daily

In [10]:
import requests
import io
import pandas as pd

# 1. Download the file text
url = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
text = requests.get(url, timeout=30).text
lines = text.strip().splitlines()

# 2. Find where the header/date row is
header_end_idx = 0
for idx, line in enumerate(lines):
    if line.lstrip().startswith(("YYYYMMDD", "Date")):
        header_end_idx = idx
        print(f"Found header at index: {idx}")
        print(f"Header line: {line}")
        break

# 3. Test reading the table text into pandas
data_text = "\n".join(lines[header_end_idx:])
df_test = pd.read_csv(io.StringIO(data_text), sep=r"\s+")

print("\nDataFrame shape:", df_test.shape)
display(df_test.head())

DataFrame shape: (13, 5)

,Product:,Daily,Heating,Degree,Days
0,Regions:,Regions::CensusDivisions,NaN,NaN,NaN
1,Weights:,Population,NaN,NaN,NaN
2,Region|20110101|20110102|20110103|20110104|201...,NaN,NaN,NaN,NaN
3,1|24|23|34|38|38|42|42|39|37|39|43|40|40|48|49...,NaN,NaN,NaN,NaN
4,2|25|25|36|35|37|42|40|44|41|41|43|42|42|46|44...,NaN,NaN,NaN,NaN

In [11]:
df = parse_cpc_daily(text)
print("Columns found:", df.columns.tolist())

Columns found: ['date', 'region', 'measure', 'weighting', 'value']

In [12]:
import requests
import importlib
import gasp.weather_cpc

# Force reload so Python picks up your saved changes from the .py file
importlib.reload(gasp.weather_cpc)
from gasp.weather_cpc import parse_cpc_daily

# Download a sample NOAA text file
url = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
text = requests.get(url, timeout=30).text

# Run your parser function
df = parse_cpc_daily(text)

# Inspect the final tidy DataFrame
print("Success! DataFrame shape:", df.shape)
display(df.head(10))

Success! DataFrame shape: (3650, 5)

       date region                    measure   weighting  value
0  20110101      1  Daily Heating Degree Days  Population     24
1  20110101      2  Daily Heating Degree Days  Population     25
2  20110101      3  Daily Heating Degree Days  Population     26
3  20110101      4  Daily Heating Degree Days  Population     51
4  20110101      5  Daily Heating Degree Days  Population     12
5  20110101      6  Daily Heating Degree Days  Population     11
6  20110101      7  Daily Heating Degree Days  Population     18
7  20110101      8  Daily Heating Degree Days  Population     47
8  20110101      9  Daily Heating Degree Days  Population     27
9  20110101  CONUS  Daily Heating Degree Days  Population     25

In [13]:
import requests
import importlib
import gasp.weather_cpc

# Force reload so Python picks up your saved changes from the .py file
importlib.reload(gasp.weather_cpc)
from gasp.weather_cpc import parse_cpc_daily

# Download a sample NOAA text file
url = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
text = requests.get(url, timeout=30).text

# Run your parser function
df = parse_cpc_daily(text)

# Inspect the final tidy DataFrame
print("Success! DataFrame shape:", df.shape)
display(df.head(10))

Success! DataFrame shape: (3650, 5)

        date region                    measure   weighting  value
0 2011-01-01      1  Daily Heating Degree Days  Population     24
1 2011-01-01      2  Daily Heating Degree Days  Population     25
2 2011-01-01      3  Daily Heating Degree Days  Population     26
3 2011-01-01      4  Daily Heating Degree Days  Population     51
4 2011-01-01      5  Daily Heating Degree Days  Population     12
5 2011-01-01      6  Daily Heating Degree Days  Population     11
6 2011-01-01      7  Daily Heating Degree Days  Population     18
7 2011-01-01      8  Daily Heating Degree Days  Population     47
8 2011-01-01      9  Daily Heating Degree Days  Population     27
9 2011-01-01  CONUS  Daily Heating Degree Days  Population     25

In [14]:
import requests
from gasp.weather_cpc import parse_cpc_daily

url_2011 = "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data/2011/Population.Heating.txt"
df_2011 = parse_cpc_daily(requests.get(url_2011, timeout=30).text)

# Check row count / days per region (should be 365)
print("Days per region in 2011:")
print(df_2011.groupby("region")["date"].count())

# Check specific dates for CONUS/US region
conus_jan1 = df_2011[(df_2011["date"] == "2011-01-01") & (df_2011["region"].str.upper() == "CONUS")]
conus_dec31 = df_2011[(df_2011["date"] == "2011-12-31") & (df_2011["region"].str.upper() == "CONUS")]

print("\nCONUS 2011-01-01 value:", conus_jan1["value"].values)
print("CONUS 2011-12-31 value:", conus_dec31["value"].values)

Days per region in 2011:
region
1        365
2        365
3        365
4        365
5        365
6        365
7        365
8        365
9        365
CONUS    365
Name: date, dtype: int64

CONUS 2011-01-01 value: [25]
CONUS 2011-12-31 value: [18]

In [1]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

NameError: name 'datetime' is not defined

In [2]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

NameError: name 'datetime' is not defined

In [3]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

NameError: name 'datetime' is not defined

In [4]:
%load_ext autoreload
%autoreload 2

In [5]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

NameError: name 'datetime' is not defined

In [1]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 366

In [1]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

ParserError: Expected 1 fields in line 3, saw 366

In [1]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

ParserError: Expected 1 fields in line 3, saw 366

In [2]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span to verify continuity
df_multi = fetch_cpc_daily("Population.Heating.txt", 2011, 2015)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))

ParserError: Expected 1 fields in line 3, saw 366

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
import inspect
from gasp.weather_cpc import parse_cpc_daily

# This will print the exact source code Python currently has loaded for the function
print(inspect.getsource(parse_cpc_daily))

def parse_cpc_daily(text: str) -> pd.DataFrame:
    lines = text.strip().splitlines()

    raw_measure = "unknown"
    raw_weighting = "unknown"
    header_end_idx = 0

    # 1. Extract metadata and locate the exact "Region|" header row
    for idx, line in enumerate(lines):
        if line.startswith("Product:"):
            val = line.split(":", 1)[1].strip().lower()
            raw_measure = "hdd" if "heating" in val else "cdd" if "cooling" in val else val
        elif line.startswith("Weights:"):
            raw_weighting = line.split(":", 1)[1].strip().lower()
        elif line.startswith("Region|") or line.lstrip().startswith("Region|"):
            header_end_idx = idx
            break

    # Fallback if "Region|" wasn't caught directly
    if header_end_idx == 0:
        pipe_counts = [line.count('|') for line in lines]
        if max(pipe_counts) > 0:
            header_end_idx = max(range(len(pipe_counts)), key=pipe_counts.__getitem__)

    # 2. Clean up table lines (skip empty/dashed lines, strip trailing pipes)
    cleaned_lines = []
    for line in lines[header_end_idx:]:
        stripped = line.strip()
        if not stripped or all(c in '-' for c in stripped):
            continue
        if stripped.endswith('|'):
            stripped = stripped[:-1]
        cleaned_lines.append(stripped)

    data_text = "\n".join(cleaned_lines)

    # 3. Parse with pandas
    df = pd.read_csv(io.StringIO(data_text), sep="|", engine="python", skipinitialspace=True)

    # Clean column whitespace and drop unnamed artifacts
    df.columns = df.columns.str.strip()
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

    # 4. Melt wide date columns to long format
    id_col = df.columns[0]
    df = df.dropna(subset=[id_col])
    date_cols = [c for c in df.columns if c != id_col]

    df_long = df.melt(
        id_vars=[id_col],
        value_vars=date_cols,
        var_name="date",
        value_name="value"
    )

    # 5. Normalize schema to Contract #4
    df_long = df_long.rename(columns={id_col: "region"})
    df_long["measure"] = raw_measure
    df_long["weighting"] = raw_weighting

    # Normalize region: CONUS -> "US"
    df_long["region"] = df_long["region"].astype(str).str.strip()
    df_long["region"] = df_long["region"].apply(lambda r: "US" if r.upper() == "CONUS" else r)

    # Convert types and filter out invalid rows
    df_long["date"] = pd.to_datetime(df_long["date"], format="%Y%m%d", errors="coerce")
    df_long = df_long.dropna(subset=["date"])
    df_long["value"] = pd.to_numeric(df_long["value"], errors="coerce")

    # Reorder and sort chronologically (oldest first)
    df_long = df_long[["date", "region", "measure", "weighting", "value"]]
    df_long = df_long.sort_values("date").reset_index(drop=True)

    return df_long

In [5]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span (now successfully handling historical files like 1981!)
df_multi = fetch_cpc_daily("Population.Heating.txt", 1981, 1985)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))
print(df_multi.head())

ParserError: Expected 1 fields in line 3, saw 366

In [1]:
from gasp.weather_cpc import fetch_cpc_daily

# Fetch a multi-year span (now successfully handling historical files like 1981!)
df_multi = fetch_cpc_daily("Population.Heating.txt", 1981, 1985)

# Check date continuity across year boundaries
print("Min date:", df_multi["date"].min())
print("Max date:", df_multi["date"].max())
print("Total rows:", len(df_multi))
print(df_multi.head())

Min date: 1981-01-01 00:00:00
Max date: 1985-12-31 00:00:00
Total rows: 18260
        date region measure   weighting  value
0 1981-01-01      1     hdd  population     51
1 1981-01-01      2     hdd  population     45
2 1981-01-01      3     hdd  population     36
3 1981-01-01      4     hdd  population     33
4 1981-01-01      5     hdd  population     24

In [4]:
# Verifies uniqueness across the full composite key required by Contract #4
full_dups = df_multi.duplicated(subset=["date", "region", "measure", "weighting"]).sum()
print("Composite duplicates:", full_dups)  # Should be 0

Composite duplicates: 0